@host = localhost
@port=5000

@user={{$randomInt 1 1000}}

### Get shopping cart for a user with some ID
GET http://{{host}}:{{port}}/shoppingcart/360

#### Adding two items to a shopping cart to random user
POST http://{{host}}:{{port}}/shoppingcart/{{user}}/items
Accept: application/json
Content-Type: application/json

[1, 2]

# ### Get all events between 0 and 20
GET http://{{host}}:{{port}}/events?start=0&end=20
Accept: application/json
