version: '3.4'

services:
    bandwidthtester.workerservice:
        image: bandwidthtesterworkerservice
        build:
            context: .
            dockerfile: BandwidthTester/Dockerfile

    seq:
        image: datalust/seq:latest
        ports:
            - "5341:80"
        environment:
            ACCEPT_EULA: Y
        restart: unless-stopped
        volumes:
            - ./seq-data:/data
