version: '3.4'

services:
    postgresql-database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=adminadmin
            - POSTGRES_DB=SampleDatabase
        ports:
            - "5432:5432"
        restart: unless-stopped
        volumes:
            - database-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:80"
        restart: unless-stopped
        volumes:
            - pgadmin:/root/.pgadmin

    postgresqlsample:
        image: postgresqlsample
        build:
            context: .
            dockerfile: PostgreSqlSample/Dockerfile
        depends_on:
            - postgresql-database

volumes:
    database-data:
    pgadmin:
