//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 
namespace FinReportWebServiceByWsdl.ServerClass {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Web.Services.WebServiceAttribute(Namespace="http://asmx.report.ru/")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FinReportServiceSoap", Namespace="http://asmx.report.ru/")]
    public abstract partial class FinReportService : System.Web.Services.WebService {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://asmx.report.ru/GetReportIdArray", RequestNamespace="http://asmx.report.ru/", ResponseNamespace="http://asmx.report.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract GetReportIdArrayResult GetReportIdArray(GetReportIdArrayArg arg);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://asmx.report.ru/GetReport", RequestNamespace="http://asmx.report.ru/", ResponseNamespace="http://asmx.report.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public abstract GetReportResult GetReport(GetReportArg arg);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.report.ru/")]
    public partial class GetReportIdArrayArg {
        
        private System.DateTime dateBeginField;
        
        private System.DateTime dateEndField;
        
        /// <remarks/>
        public System.DateTime DateBegin {
            get {
                return this.dateBeginField;
            }
            set {
                this.dateBeginField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateEnd {
            get {
                return this.dateEndField;
            }
            set {
                this.dateEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.report.ru/")]
    public partial class FinReport {
        
        private int reportIDField;
        
        private System.DateTime dateField;
        
        private string infoField;
        
        /// <remarks/>
        public int ReportID {
            get {
                return this.reportIDField;
            }
            set {
                this.reportIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.report.ru/")]
    public partial class GetReportResult {
        
        private FinReport reportField;
        
        /// <remarks/>
        public FinReport Report {
            get {
                return this.reportField;
            }
            set {
                this.reportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.report.ru/")]
    public partial class GetReportArg {
        
        private int reportIDField;
        
        /// <remarks/>
        public int ReportID {
            get {
                return this.reportIDField;
            }
            set {
                this.reportIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.report.ru/")]
    public partial class GetReportIdArrayResult {
        
        private int[] reportIdArrayField;
        
        /// <remarks/>
        public int[] ReportIdArray {
            get {
                return this.reportIdArrayField;
            }
            set {
                this.reportIdArrayField = value;
            }
        }
    }
}
