//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 
namespace FinReportWebServiceClient.ProxyClass {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FinReportServiceSoap", Namespace="http://asmx.report.ru/")]
    public partial class FinReportService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetReportIdArrayOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportOperationCompleted;
        
        /// <remarks/>
        public FinReportService() {
            this.Url = "https://localhost:44394/FinReportByWsdl.asmx";
        }
        
        /// <remarks/>
        public event GetReportIdArrayCompletedEventHandler GetReportIdArrayCompleted;
        
        /// <remarks/>
        public event GetReportCompletedEventHandler GetReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://asmx.report.ru/GetReportIdArray", RequestNamespace="http://asmx.report.ru/", ResponseNamespace="http://asmx.report.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetReportIdArrayResult GetReportIdArray(GetReportIdArrayArg arg) {
            object[] results = this.Invoke("GetReportIdArray", new object[] {
                        arg});
            return ((GetReportIdArrayResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetReportIdArray(GetReportIdArrayArg arg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetReportIdArray", new object[] {
                        arg}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetReportIdArrayResult EndGetReportIdArray(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetReportIdArrayResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportIdArrayAsync(GetReportIdArrayArg arg) {
            this.GetReportIdArrayAsync(arg, null);
        }
        
        /// <remarks/>
        public void GetReportIdArrayAsync(GetReportIdArrayArg arg, object userState) {
            if ((this.GetReportIdArrayOperationCompleted == null)) {
                this.GetReportIdArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportIdArrayOperationCompleted);
            }
            this.InvokeAsync("GetReportIdArray", new object[] {
                        arg}, this.GetReportIdArrayOperationCompleted, userState);
        }
        
        private void OnGetReportIdArrayOperationCompleted(object arg) {
            if ((this.GetReportIdArrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportIdArrayCompleted(this, new GetReportIdArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://asmx.report.ru/GetReport", RequestNamespace="http://asmx.report.ru/", ResponseNamespace="http://asmx.report.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetReportResult GetReport(GetReportArg arg) {
            object[] results = this.Invoke("GetReport", new object[] {
                        arg});
            return ((GetReportResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetReport(GetReportArg arg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetReport", new object[] {
                        arg}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetReportResult EndGetReport(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetReportResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportAsync(GetReportArg arg) {
            this.GetReportAsync(arg, null);
        }
        
        /// <remarks/>
        public void GetReportAsync(GetReportArg arg, object userState) {
            if ((this.GetReportOperationCompleted == null)) {
                this.GetReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportOperationCompleted);
            }
            this.InvokeAsync("GetReport", new object[] {
                        arg}, this.GetReportOperationCompleted, userState);
        }
        
        private void OnGetReportOperationCompleted(object arg) {
            if ((this.GetReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportCompleted(this, new GetReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.report.ru/")]
    public partial class GetReportIdArrayArg {
        
        private System.DateTime dateBeginField;
        
        private System.DateTime dateEndField;
        
        /// <remarks/>
        public System.DateTime DateBegin {
            get {
                return this.dateBeginField;
            }
            set {
                this.dateBeginField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateEnd {
            get {
                return this.dateEndField;
            }
            set {
                this.dateEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.report.ru/")]
    public partial class FinReport {
        
        private int reportIDField;
        
        private System.DateTime dateField;
        
        private string infoField;
        
        /// <remarks/>
        public int ReportID {
            get {
                return this.reportIDField;
            }
            set {
                this.reportIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.report.ru/")]
    public partial class GetReportResult {
        
        private FinReport reportField;
        
        /// <remarks/>
        public FinReport Report {
            get {
                return this.reportField;
            }
            set {
                this.reportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.report.ru/")]
    public partial class GetReportArg {
        
        private int reportIDField;
        
        /// <remarks/>
        public int ReportID {
            get {
                return this.reportIDField;
            }
            set {
                this.reportIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://asmx.report.ru/")]
    public partial class GetReportIdArrayResult {
        
        private int[] reportIdArrayField;
        
        /// <remarks/>
        public int[] ReportIdArray {
            get {
                return this.reportIdArrayField;
            }
            set {
                this.reportIdArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetReportIdArrayCompletedEventHandler(object sender, GetReportIdArrayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportIdArrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportIdArrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetReportIdArrayResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetReportIdArrayResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void GetReportCompletedEventHandler(object sender, GetReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetReportResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetReportResult)(this.results[0]));
            }
        }
    }
}
