# docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo:4.4.7

version: "3.3"

services:
    mongo:
        image: mongo:4.4.7
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodbdata:/data/db

volumes:
    mongodbdata:
