### Get shopping cart for a user with ID 123
GET https://localhost:5001/shoppingcart/123

#### Adding two items to a shopping cart
POST https://localhost:5001/shoppingcart/123/items
Accept: application/json
Content-Type: application/json

[1, 2]

### Get all events between 0 and 20
GET https://localhost:5001/events?start=0&end=20
Accept: application/json
